### ISSUE TITLE
Relative coordinates ? 

### ISSUE THREAD

**Issue by drhisham-code** [data-niklas/gestures#1]
Does it require absolute or relative coordinates ?

**Comment by data-niklas** [comment]
gesture_start() takes any coordinates
gesture_track() coordinates should be absolute, the x and y difference between the coordinates is calculated automatically
```
int xdif = x - gesture_recorder->x;
int ydif = y - gesture_recorder->y;
```

Keep in mind though, that the implementation could be improved, the linked list is inefficient (in comparison to other vector implementations)

**Comment by drhisham-code** [comment]
Thanks for answering quickly 😊
